apiVersion: 1

datasources:
  - name: tsdb
    type: postgres
    url: timescaledb:5432
    database: test_iot
    user: postgres
    secureJsonData:
      password: 'postgres1234'
    jsonData:
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400 # 906=9.6, 1000=10, ...
      timescaledb: true
      timeInterval: 5m