{
 "title": "Test Drive",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Coefficient of Performance",
   "type": "gauge",
   "description": "Average Coefficient of Performance (COP) \nover time range.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "rawSql": "with cba as (\r\n\tselect bucket, (\r\n    CASE\r\n      WHEN max_value >= lag(max_value) OVER w\r\n        THEN max_value - lag(max_value) OVER w\r\n      WHEN lag(max_value) OVER w IS NULL THEN NULL\r\n      ELSE max_value\r\n    END\r\n  ) AS \"input\"\r\n\tFROM measurements_daily\r\n\tWHERE parameter_id = 1\r\n\tWINDOW w AS (ORDER BY bucket)\r\n),\r\ncbb as (\r\n\tselect bucket as \"output_bucket\", (\r\n    CASE\r\n      WHEN max_value >= lag(max_value) OVER w\r\n        THEN max_value - lag(max_value) OVER w\r\n      WHEN lag(max_value) OVER w IS NULL THEN NULL\r\n      ELSE max_value\r\n    END\r\n  ) AS \"output\"\r\n\tFROM measurements_daily\r\n\tWHERE parameter_id = 2\r\n\tWINDOW w AS (ORDER BY bucket)\r\n)\r\nselect avg(\"input\") as \"input\", avg(\"output\") as \"output\" from cba join cbb on cba.bucket = output_bucket\r\nwhere $__timeFilter(cba.bucket)\r\n;"
    }
   ]
  },
  {
   "title": "Latest Measurements",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT me.measure_time, \r\n(select parameter_name from measurement_types where parameter_id = me.parameter_id), \r\n(select sensor_name from locations where location_id = me.location_id), \r\nme.v\r\nFROM measurements me ORDER BY measure_time DESC LIMIT 50"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT me.bucket, \r\n(select parameter_name from measurement_types where parameter_id = me.parameter_id), \r\nme.avg_value\r\nFROM measurements_hourly me \r\nWHERE me.parameter_id = 3\r\nAND $__timeFilter(me.bucket)\r\nORDER BY me.bucket DESC\r\n;"
    }
   ]
  }
 ]
}